[package]
name = "coora_engine"
version = {workspace=true}
edition = {workspace=true}
authors = {workspace=true}
documentation = {workspace=true}
license-file = {workspace=true}
readme = {workspace=true}
description = {workspace=true}
repository = {workspace=true}

[dependencies]
rgb = {workspace = true}
anyhow = {workspace = true}
wasmi = {workspace = true}
extend = {workspace = true}

[dev-dependencies]
forky_core = {workspace = true}
sweet = {workspace = true}
coora_bindings = {workspace = true}
# [build-dependencies]

[[test]]
name = "sweet"
path = "test/sweet.rs"
harness = false
